#! bash
# bash completion for the `gem` command.
#
# Copyright (c) 2008 Daniel Luz <dev at mernen dot com>.
# Distributed under the MIT license.
# http://mernen.com/projects/completion-ruby
#
# To use, source this file on bash:
#   . completion-gem

__gem() {
  local cur="$2"
  local prev="$3"
  COMPREPLY=()

  local options="
    -h --help -v --version -V --verbose --no-verbose -q --quiet
    --config-file --backtrace --debug"
  local commands="
    build cert check cleanup contents dependency environment fetch
    generate_index help install list lock mirror outdated pristine
    query rdoc search server sources specification stale uninstall
    unpack update which"

  local gem_command
  __gem_get_command

  case "$prev" in
    --config-file)
      # leave COMPREPLY blank, let the default handle it
      return;;
  esac

  local choices
  case "$gem_command" in
    "")
      choices="$commands"
      ;;
    help)
      choices="commands examples platforms $commands"
      ;;
  esac
  [[ "$cur" == -* ]] && choices="$options"
  COMPREPLY=($(compgen -W "$choices" -- "$cur"))
}

__gem_get_command() {
  local i
  for ((i=1; i < $COMP_CWORD; ++i)); do
    local arg="${COMP_WORDS[$i]}"

    case "$arg" in
      -h | --help | -v | --version)
        # these two options are command-killers
        gem_command=-
        return;;
      --config-file)
        # skip argument
        ((++i));;
      [^-]*)
        gem_command="$arg"
        return;;
    esac
  done
}

complete -F __gem -o default gem
# Ruby 1.9 suffix on Debian distros
complete -F __gem -o default gem1.9
# JRuby
complete -F __gem -o default jgem
# vim: ai ft=sh sw=2 sts=2 et
