#! bash
# bash completion for the `rails` command and rails scripts.
#
# Copyright (c) 2008 Daniel Luz <dev at mernen dot com>.
# Distributed under the MIT license.
# http://mernen.com/projects/completion-ruby
#
# To use, source this file on bash:
#   . completion-rails

__rails_script_server() {
  local cur="$2"
  local prev="$3"
  COMPREPLY=()

  case "$prev" in
    -e | --environment)
      __rails_complete_environments "$cur"
      return;;
    *)
      if [[ "$cur" == -* ]]; then
        local options="
          -p --port -b --binding -d --daemon -u --debugger
	  -e --environment"
        COMPREPLY=($(compgen -W "$options" -- "$cur"))
      fi
  esac
}

__rails_script_console() {
  local cur="$2"
  local prev="$3"
  COMPREPLY=()
  if [[ "$cur" == -* ]]; then
    local options="-s --sandbox --irb"
    COMPREPLY=($(compgen -W "$options" -- "$cur"))
  elif [[ "$prev" == "--irb" ]]; then
    COMPREPLY=($(compgen -A command -- "$cur"))
  else
    __rails_complete_environments "$cur"
  fi
}

__rails_complete_environments() {
  # hardcoded list of environments... for now?
  local environments="development test production"
  COMPREPLY=($(compgen -W "$environments" -- "$1"))
}

complete -F __rails_script_server -o default script/server
complete -F __rails_script_console -o default script/console
# vim: ai ft=sh sw=2 sts=2 et
